-- DDL Health Clinic

--CRIAR BANCO

CREATE DATABASE Projeto_Health_ClinicTD;
USE Projeto_Health_ClinicTD;

--CRIAR TABELAS

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TituloTipoUsuario VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(50) NOT NULL,
	RazaoSocial VARCHAR(150) NOT NULL,
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
	Endereco VARCHAR(200) NOT NULL,
	HorarioAbertura TIME NOT NULL,
	HorarioFechamento TIME NOT NULL
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	TituloEspecialidade VARCHAR(60) NOT NULL,
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario) NOT NULL,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Senha  VARCHAR(50) NOT NULL
)

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	RG VARCHAR(7) NOT NULL UNIQUE,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR(13) NOT NULL UNIQUE
)

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica (IdClinica) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade (IdEspecialidade) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	CRM VARCHAR(8) NOT NULL UNIQUE
)